name: 'Test-Terraform'

on:
  push:
    branches-ignore:
    - main

jobs:
  terraform:
    name: 'Main Pipeline'
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.TEST_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      CI_CD_ROLE_ARN: ${{ secrets.CI_CD_ROLE_ARN }}
      DESTROY: '0'
      TF_IN_AUTOMATION: 1
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    

    # Checkout the repository to the GitHub Actions runner
    steps:

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.5


    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Init
      run: |
          mkdir ~/.aws/
          echo -e "[default]" > ~/.aws/credentials
          echo -e "aws_access_key_id=$AWS_ACCESS_KEY_ID">> ~/.aws/credentials
          echo -e "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY">> ~/.aws/credentials
          echo -e "[default]" > ~/.aws/config
          echo -e "region = us-east-1" >> ~/.aws/config
          echo -e "output = json" >> ~/.aws/config
          echo -e "[profile home]" >> ~/.aws/config
          echo -e "role_arn=arn:aws:iam::$ACCOUNT_ID:role/$CI_CD_ROLE_ARN" >> ~/.aws/config
          echo -e "source_profile = default" >> ~/.aws/config
          echo -e "region = us-east-1" >> ~/.aws/config
          echo -e "output = json" >> ~/.aws/config
          cat <<EOF > backend.tf
          terraform {
            backend "s3" {
              bucket = "terraform-statefiles-karl-cardenas-coding"
              key    = "aws-code-signing-example/state.tfstate"
              region = "us-east-1"
              profile = "home"
              encrypt        = true
            }
          }
          EOF
          cat backend.tf *&& terraform init
    # Generates an execution plan for Terraform
    - name: Terraform Plan
      if: env.DESTROY != '1'
      run: terraform plan -out="tf-plan"

  
      # On push to master, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      if: env.DESTROY != '1'
      run: |
         terraform apply "tf-plan" -auto-approve

    - name: Terraform destroy
      if:  env.DESTROY == '1'
      run: terraform destroy -auto-approve



